/* Hadis ilminin önemli simaları — ad ve hicrî vefat yılı.
   Oyun verisi olarak üretildi (2026-09-09).

   Erken dönem yılları RİVAYET HARİTASINDAN alındı (app/silsileVeri.js),
   yani sitedeki iki veri kendi içinde tutarlı. O yılların bir kısmı
   DİA'dan, kalanı İbn Hacer'in Takrîb'inden geliyor. Kütüb-i Sitte
   müelliflerinden sonrası harita kapsamı dışında kaldığı için elle
   yazıldı.

   `devir` alanı zorluk kademelendirmesi için. Sahâbe ve musannifler
   kolay, ricâl ile geç dönem zor. */
export type HadisSima = { ad: string; olum: number; devir: string };

export const HADIS_SIMALARI: HadisSima[] = [
  { ad: "Ebû Bekir es-Sıddîk", olum: 13, devir: "Sahâbe" },
  { ad: "Ömer b. el-Hattâb", olum: 23, devir: "Sahâbe" },
  { ad: "Osman b. Affân", olum: 35, devir: "Sahâbe" },
  { ad: "Ali b. Ebî Tâlib", olum: 40, devir: "Sahâbe" },
  { ad: "Muâz b. Cebel", olum: 18, devir: "Sahâbe" },
  { ad: "Übey b. Kâ‘b", olum: 33, devir: "Sahâbe" },
  { ad: "Zeyd b. Sâbit", olum: 45, devir: "Sahâbe" },
  { ad: "Abdullah b. Mes‘ûd", olum: 32, devir: "Sahâbe" },
  { ad: "Ebü'd-Derdâ", olum: 32, devir: "Sahâbe" },
  { ad: "Selmân-ı Fârisî", olum: 36, devir: "Sahâbe" },
  { ad: "Ebû Mûsâ el-Eş‘arî", olum: 42, devir: "Sahâbe" },
  { ad: "Üsâme b. Zeyd", olum: 54, devir: "Sahâbe" },
  { ad: "Hafsa bint Ömer", olum: 45, devir: "Sahâbe" },
  { ad: "Ümmü Seleme", olum: 59, devir: "Sahâbe" },
  { ad: "Âişe bint Ebî Bekir", olum: 58, devir: "Sahâbe" },
  { ad: "Ebû Hüreyre", olum: 58, devir: "Sahâbe" },
  { ad: "Abdullah b. Abbâs", olum: 68, devir: "Sahâbe" },
  { ad: "Abdullah b. Ömer", olum: 73, devir: "Sahâbe" },
  { ad: "Câbir b. Abdullah", olum: 78, devir: "Sahâbe" },
  { ad: "Enes b. Mâlik", olum: 93, devir: "Sahâbe" },
  { ad: "Ebû Saîd el-Hudrî", olum: 74, devir: "Sahâbe" },
  { ad: "Abdullah b. Amr b. el-Âs", olum: 63, devir: "Sahâbe" },
  { ad: "Berâ b. Âzib", olum: 71, devir: "Sahâbe" },
  { ad: "Abdullah b. ez-Zübeyr", olum: 73, devir: "Sahâbe" },
  { ad: "Alkame b. Kays en-Nehaî", olum: 62, devir: "Tâbiîn" },
  { ad: "Mesrûk b. el-Ecda‘", olum: 63, devir: "Tâbiîn" },
  { ad: "Esved b. Yezîd en-Nehaî", olum: 75, devir: "Tâbiîn" },
  { ad: "Saîd b. el-Müseyyeb", olum: 94, devir: "Tâbiîn" },
  { ad: "Urve b. ez-Zübeyr", olum: 94, devir: "Tâbiîn" },
  { ad: "Ali b. el-Hüseyin (Zeynelâbidîn)", olum: 94, devir: "Tâbiîn" },
  { ad: "Kâsım b. Muhammed b. Ebî Bekir", olum: 106, devir: "Tâbiîn" },
  { ad: "Sâlim b. Abdillâh b. Ömer", olum: 106, devir: "Tâbiîn" },
  { ad: "İbrâhim en-Nehaî", olum: 96, devir: "Tâbiîn" },
  { ad: "Âmir b. Şerâhîl eş-Şa‘bî", olum: 104, devir: "Tâbiîn" },
  { ad: "Tâvûs b. Keysân", olum: 106, devir: "Tâbiîn" },
  { ad: "Mücâhid b. Cebr", olum: 103, devir: "Tâbiîn" },
  { ad: "İkrime mevlâ İbn Abbâs", olum: 105, devir: "Tâbiîn" },
  { ad: "Atâ b. Ebî Rebâh", olum: 114, devir: "Tâbiîn" },
  { ad: "Hasan-ı Basrî", olum: 110, devir: "Tâbiîn" },
  { ad: "Muhammed b. Sîrîn", olum: 110, devir: "Tâbiîn" },
  { ad: "Nâfi‘ mevlâ İbn Ömer", olum: 117, devir: "Tâbiîn" },
  { ad: "Mekhûl eş-Şâmî", olum: 112, devir: "Tâbiîn" },
  { ad: "İbn Şihâb ez-Zührî", olum: 124, devir: "Tâbiîn" },
  { ad: "Katâde b. Diâme es-Sedûsî", olum: 117, devir: "Tâbiîn" },
  { ad: "A‘meş", olum: 148, devir: "Tebeu't-tâbiîn" },
  { ad: "Evzâî", olum: 157, devir: "Tebeu't-tâbiîn" },
  { ad: "Ma‘mer b. Râşid", olum: 153, devir: "Tebeu't-tâbiîn" },
  { ad: "İbn Cüreyc", olum: 150, devir: "Tebeu't-tâbiîn" },
  { ad: "Süfyân es-Sevrî", olum: 161, devir: "Tebeu't-tâbiîn" },
  { ad: "Mâlik b. Enes", olum: 179, devir: "Tebeu't-tâbiîn" },
  { ad: "Şu‘be b. el-Haccâc", olum: 160, devir: "Tebeu't-tâbiîn" },
  { ad: "Hammâd b. Seleme", olum: 167, devir: "Tebeu't-tâbiîn" },
  { ad: "Leys b. Sa‘d", olum: 175, devir: "Tebeu't-tâbiîn" },
  { ad: "Hammâd b. Zeyd", olum: 179, devir: "Tebeu't-tâbiîn" },
  { ad: "Abdullah b. el-Mübârek", olum: 181, devir: "Tebeu't-tâbiîn" },
  { ad: "Vekî‘ b. el-Cerrâh", olum: 197, devir: "Tebeu't-tâbiîn" },
  { ad: "Süfyân b. Uyeyne", olum: 198, devir: "Tebeu't-tâbiîn" },
  { ad: "Yahyâ b. Saîd el-Kattân", olum: 198, devir: "Tebeu't-tâbiîn" },
  { ad: "Abdurrahman b. Mehdî", olum: 198, devir: "Tebeu't-tâbiîn" },
  { ad: "Ebû Dâvûd et-Tayâlisî", olum: 204, devir: "Musannifler" },
  { ad: "Abdürrezzâk b. Hemmâm", olum: 211, devir: "Musannifler" },
  { ad: "Saîd b. Mansûr", olum: 227, devir: "Musannifler" },
  { ad: "İbn Ebî Şeybe", olum: 235, devir: "Musannifler" },
  { ad: "İshak b. Râhûye", olum: 238, devir: "Musannifler" },
  { ad: "Ahmed b. Hanbel", olum: 241, devir: "Musannifler" },
  { ad: "Humeydî, Abdullah b. Zübeyr", olum: 219, devir: "Musannifler" },
  { ad: "Dârimî", olum: 255, devir: "Musannifler" },
  { ad: "Buhârî", olum: 256, devir: "Musannifler" },
  { ad: "Müslim", olum: 261, devir: "Musannifler" },
  { ad: "İbn Mâce", olum: 273, devir: "Musannifler" },
  { ad: "Ebû Dâvûd es-Sicistânî", olum: 275, devir: "Musannifler" },
  { ad: "Tirmizî", olum: 279, devir: "Musannifler" },
  { ad: "Nesâî", olum: 303, devir: "Musannifler" },
  { ad: "Bezzâr", olum: 292, devir: "Musannifler" },
  { ad: "Ebû Ya‘lâ el-Mevsılî", olum: 307, devir: "Musannifler" },
  { ad: "İbn Huzeyme", olum: 311, devir: "Musannifler" },
  { ad: "Taberânî", olum: 360, devir: "Musannifler" },
  { ad: "Dârekutnî", olum: 385, devir: "Musannifler" },
  { ad: "Hâkim en-Nîsâbûrî", olum: 405, devir: "Musannifler" },
  { ad: "Beyhakī", olum: 458, devir: "Musannifler" },
  { ad: "Yahyâ b. Maîn", olum: 233, devir: "Ricâl ve ilel" },
  { ad: "Ali b. el-Medînî", olum: 234, devir: "Ricâl ve ilel" },
  { ad: "Ebû Zür‘a er-Râzî", olum: 264, devir: "Ricâl ve ilel" },
  { ad: "Ebû Hâtim er-Râzî", olum: 277, devir: "Ricâl ve ilel" },
  { ad: "İclî", olum: 261, devir: "Ricâl ve ilel" },
  { ad: "Cûzcânî", olum: 259, devir: "Ricâl ve ilel" },
  { ad: "Fesevî, Ya‘kūb b. Süfyân", olum: 277, devir: "Ricâl ve ilel" },
  { ad: "Ukaylî", olum: 322, devir: "Ricâl ve ilel" },
  { ad: "İbn Ebî Hâtim", olum: 327, devir: "Ricâl ve ilel" },
  { ad: "İbn Hibbân", olum: 354, devir: "Ricâl ve ilel" },
  { ad: "İbn Adî", olum: 365, devir: "Ricâl ve ilel" },
  { ad: "Hatîb el-Bağdâdî", olum: 463, devir: "Ricâl ve ilel" },
  { ad: "Mizzî", olum: 742, devir: "Ricâl ve ilel" },
  { ad: "Zehebî", olum: 748, devir: "Ricâl ve ilel" },
  { ad: "İbn Hacer el-Askalânî", olum: 852, devir: "Ricâl ve ilel" },
  { ad: "Şâfiî", olum: 204, devir: "Usûl ve şerh" },
  { ad: "Râmhürmüzî", olum: 360, devir: "Usûl ve şerh" },
  { ad: "İbn Abdilberr", olum: 463, devir: "Usûl ve şerh" },
  { ad: "İbn Hazm", olum: 456, devir: "Usûl ve şerh" },
  { ad: "Kādî İyâz", olum: 544, devir: "Usûl ve şerh" },
  { ad: "İbnü'l-Cevzî", olum: 597, devir: "Usûl ve şerh" },
  { ad: "İbnü'l-Esîr, Mecdüddin", olum: 606, devir: "Usûl ve şerh" },
  { ad: "İbnü's-Salâh", olum: 643, devir: "Usûl ve şerh" },
  { ad: "Münzirî", olum: 656, devir: "Usûl ve şerh" },
  { ad: "Nevevî", olum: 676, devir: "Usûl ve şerh" },
  { ad: "İbn Kesîr", olum: 774, devir: "Usûl ve şerh" },
  { ad: "İbn Receb el-Hanbelî", olum: 795, devir: "Usûl ve şerh" },
  { ad: "Kirmânî", olum: 786, devir: "Usûl ve şerh" },
  { ad: "Irâkī, Zeynüddin", olum: 806, devir: "Usûl ve şerh" },
  { ad: "Heysemî", olum: 807, devir: "Usûl ve şerh" },
  { ad: "İbnü'l-Mülakkın", olum: 804, devir: "Usûl ve şerh" },
  { ad: "Bulkīnî, Sirâcüddin", olum: 805, devir: "Usûl ve şerh" },
  { ad: "Aynî", olum: 855, devir: "Usûl ve şerh" },
  { ad: "Sehâvî", olum: 902, devir: "Usûl ve şerh" },
  { ad: "Süyûtî", olum: 911, devir: "Usûl ve şerh" },
  { ad: "Kastallânî", olum: 923, devir: "Usûl ve şerh" },
  { ad: "Ali el-Kārî", olum: 1014, devir: "Geç dönem" },
  { ad: "Münâvî", olum: 1031, devir: "Geç dönem" },
  { ad: "Aclûnî", olum: 1162, devir: "Geç dönem" },
  { ad: "Şah Veliyyullah ed-Dihlevî", olum: 1176, devir: "Geç dönem" },
  { ad: "Zebîdî, Murtazâ", olum: 1205, devir: "Geç dönem" },
  { ad: "Leknevî", olum: 1304, devir: "Geç dönem" },
  { ad: "Kettânî, Muhammed b. Ca‘fer", olum: 1345, devir: "Geç dönem" },
  { ad: "Ahmed Muhammed Şâkir", olum: 1377, devir: "Geç dönem" },
  { ad: "Elbânî", olum: 1420, devir: "Geç dönem" },
];
