/* Hadis ilminin önemli simaları — ad, hicrî vefat yılı, devir, zorluk.
   Oyun verisi olarak üretildi (2026-09-09).

   ERKEN DÖNEM YILLARI RİVAYET HARİTASINDAN alınıyor
   (app/silsileVeri.js), elle yazılmıyor. Sebebi tutarlılık: aynı
   sitede aynı kişiye iki farklı yıl yazmak oyunu haritayla çelişkiye
   düşürürdü. Harita yıllarının bir kısmı DİA'dan, kalanı İbn Hacer'in
   Takrîb'inden geliyor. Kütüb-i Sitte müelliflerinden sonrası harita
   kapsamı dışında kaldığı için elle yazıldı.

   `zorluk` 1-5. 1 herkesin bildiği, 5 alan uzmanının bildiği. Oyunun
   soru eşi bu alandan kurulabilir — Buhârî ile Berdîcî aynı soruda
   çıkmasın diye.

   Üreteci scratchpad'de (liste2.cjs). Harita yılları değişirse
   yeniden koşturulmalı. */
export type HadisSima = {
  ad: string;
  /** Hicrî vefat yılı. Oyunun sıralama ve karşılaştırma alanı budur. */
  olum: number;
  devir: string;
  zorluk: 1 | 2 | 3 | 4 | 5;
  /** Mîlâdî karşılık, yalnızca hicrî 1300'den sonrası için.
   *  Gösterimde `olum/miladi` biçiminde okunur (1304/1886). Ayrı bir
   *  alan, çünkü `olum` sayısal kalmalı — oyun onunla sıralıyor. */
  miladi?: number;
};

export const HADIS_SIMALARI: HadisSima[] = [
  { ad: "Ebû Bekir es-Sıddîk", olum: 13, devir: "Sahâbe", zorluk: 1 },
  { ad: "Ömer b. el-Hattâb", olum: 23, devir: "Sahâbe", zorluk: 1 },
  { ad: "Osman b. Affân", olum: 35, devir: "Sahâbe", zorluk: 1 },
  { ad: "Ali b. Ebî Tâlib", olum: 40, devir: "Sahâbe", zorluk: 1 },
  { ad: "Ebû Hüreyre", olum: 58, devir: "Sahâbe", zorluk: 1 },
  { ad: "Abdullah b. Ömer", olum: 73, devir: "Sahâbe", zorluk: 1 },
  { ad: "Âişe bint Ebî Bekir", olum: 58, devir: "Sahâbe", zorluk: 1 },
  { ad: "Abdullah b. Abbâs", olum: 68, devir: "Sahâbe", zorluk: 1 },
  { ad: "Enes b. Mâlik", olum: 93, devir: "Sahâbe", zorluk: 1 },
  { ad: "Câbir b. Abdullah", olum: 78, devir: "Sahâbe", zorluk: 2 },
  { ad: "Ebû Saîd el-Hudrî", olum: 74, devir: "Sahâbe", zorluk: 2 },
  { ad: "Abdullah b. Mes‘ûd", olum: 32, devir: "Sahâbe", zorluk: 1 },
  { ad: "Abdullah b. Amr b. el-Âs", olum: 63, devir: "Sahâbe", zorluk: 2 },
  { ad: "Zeyd b. Sâbit", olum: 45, devir: "Sahâbe", zorluk: 2 },
  { ad: "Muâz b. Cebel", olum: 18, devir: "Sahâbe", zorluk: 2 },
  { ad: "Übey b. Kâ‘b", olum: 33, devir: "Sahâbe", zorluk: 2 },
  { ad: "Ebü'd-Derdâ", olum: 32, devir: "Sahâbe", zorluk: 2 },
  { ad: "Selmân-ı Fârisî", olum: 36, devir: "Sahâbe", zorluk: 2 },
  { ad: "Ebû Mûsâ el-Eş‘arî", olum: 42, devir: "Sahâbe", zorluk: 2 },
  { ad: "Berâ b. Âzib", olum: 71, devir: "Sahâbe", zorluk: 3 },
  { ad: "Abdullah b. ez-Zübeyr", olum: 73, devir: "Sahâbe", zorluk: 2 },
  { ad: "Üsâme b. Zeyd", olum: 54, devir: "Sahâbe", zorluk: 3 },
  { ad: "Hafsa bint Ömer", olum: 45, devir: "Sahâbe", zorluk: 3 },
  { ad: "Ümmü Seleme", olum: 59, devir: "Sahâbe", zorluk: 2 },
  { ad: "Sa‘d b. Ebî Vakkās", olum: 55, devir: "Sahâbe", zorluk: 2 },
  { ad: "Talha b. Ubeydillâh", olum: 36, devir: "Sahâbe", zorluk: 2 },
  { ad: "Abdurrahman b. Avf", olum: 32, devir: "Sahâbe", zorluk: 2 },
  { ad: "Ebû Zer el-Gıfârî", olum: 32, devir: "Sahâbe", zorluk: 2 },
  { ad: "Huzeyfe b. el-Yemân", olum: 36, devir: "Sahâbe", zorluk: 2 },
  { ad: "Bilâl-i Habeşî", olum: 20, devir: "Sahâbe", zorluk: 2 },
  { ad: "Mikdâd b. el-Esved", olum: 33, devir: "Sahâbe", zorluk: 3 },
  { ad: "Ubâde b. es-Sâmit", olum: 34, devir: "Sahâbe", zorluk: 3 },
  { ad: "Ebû Eyyûb el-Ensârî", olum: 52, devir: "Sahâbe", zorluk: 2 },
  { ad: "Sehl b. Sa‘d es-Sâidî", olum: 88, devir: "Sahâbe", zorluk: 3 },
  { ad: "Vâsile b. el-Eska‘", olum: 85, devir: "Sahâbe", zorluk: 4 },
  { ad: "Ebû Ümâme el-Bâhilî", olum: 86, devir: "Sahâbe", zorluk: 3 },
  { ad: "Ebü't-Tufeyl Âmir b. Vâsile", olum: 100, devir: "Sahâbe", zorluk: 3 },
  { ad: "Câbir b. Semüre", olum: 74, devir: "Sahâbe", zorluk: 3 },
  { ad: "Nu‘mân b. Beşîr", olum: 64, devir: "Sahâbe", zorluk: 3 },
  { ad: "Mugīre b. Şu‘be", olum: 50, devir: "Sahâbe", zorluk: 2 },
  { ad: "İmrân b. Husayn", olum: 52, devir: "Sahâbe", zorluk: 3 },
  { ad: "Semüre b. Cündeb el-Fezârî", olum: 58, devir: "Sahâbe", zorluk: 3 },
  { ad: "Ebû Bekre es-Sekafî", olum: 52, devir: "Sahâbe", zorluk: 3 },
  { ad: "Zeyd b. Erkam", olum: 68, devir: "Sahâbe", zorluk: 3 },
  { ad: "Hasan b. Ali", olum: 49, devir: "Sahâbe", zorluk: 2 },
  { ad: "Hüseyin b. Ali", olum: 61, devir: "Sahâbe", zorluk: 1 },
  { ad: "Fâtıma bint Resûlillâh", olum: 11, devir: "Sahâbe", zorluk: 1 },
  { ad: "Esmâ bint Ebî Bekir", olum: 73, devir: "Sahâbe", zorluk: 3 },
  { ad: "Alkame b. Kays en-Nehaî", olum: 62, devir: "Tâbiîn", zorluk: 3 },
  { ad: "Mesrûk b. el-Ecda‘", olum: 63, devir: "Tâbiîn", zorluk: 3 },
  { ad: "Esved b. Yezîd en-Nehaî", olum: 75, devir: "Tâbiîn", zorluk: 3 },
  { ad: "Saîd b. el-Müseyyeb", olum: 94, devir: "Tâbiîn", zorluk: 2 },
  { ad: "Urve b. ez-Zübeyr", olum: 94, devir: "Tâbiîn", zorluk: 2 },
  { ad: "Ali b. el-Hüseyin (Zeynelâbidîn)", olum: 94, devir: "Tâbiîn", zorluk: 2 },
  { ad: "Kâsım b. Muhammed b. Ebî Bekir", olum: 106, devir: "Tâbiîn", zorluk: 3 },
  { ad: "Sâlim b. Abdillâh b. Ömer", olum: 106, devir: "Tâbiîn", zorluk: 3 },
  { ad: "İbrâhim en-Nehaî", olum: 96, devir: "Tâbiîn", zorluk: 2 },
  { ad: "Âmir b. Şerâhîl eş-Şa‘bî", olum: 104, devir: "Tâbiîn", zorluk: 2 },
  { ad: "Tâvûs b. Keysân", olum: 106, devir: "Tâbiîn", zorluk: 3 },
  { ad: "Mücâhid b. Cebr", olum: 103, devir: "Tâbiîn", zorluk: 2 },
  { ad: "İkrime mevlâ İbn Abbâs", olum: 105, devir: "Tâbiîn", zorluk: 2 },
  { ad: "Atâ b. Ebî Rebâh", olum: 114, devir: "Tâbiîn", zorluk: 2 },
  { ad: "Hasan-ı Basrî", olum: 110, devir: "Tâbiîn", zorluk: 1 },
  { ad: "Muhammed b. Sîrîn", olum: 110, devir: "Tâbiîn", zorluk: 2 },
  { ad: "Nâfi‘ mevlâ İbn Ömer", olum: 117, devir: "Tâbiîn", zorluk: 2 },
  { ad: "Mekhûl eş-Şâmî", olum: 112, devir: "Tâbiîn", zorluk: 3 },
  { ad: "İbn Şihâb ez-Zührî", olum: 124, devir: "Tâbiîn", zorluk: 1 },
  { ad: "Katâde b. Diâme es-Sedûsî", olum: 117, devir: "Tâbiîn", zorluk: 2 },
  { ad: "Şüreyh b. el-Hâris el-Kādî", olum: 80, devir: "Tâbiîn", zorluk: 3 },
  { ad: "Ebû Vâil Şakīk b. Seleme", olum: 82, devir: "Tâbiîn", zorluk: 4 },
  { ad: "Rib‘î b. Hırâş", olum: 101, devir: "Tâbiîn", zorluk: 4 },
  { ad: "Ebû İdrîs el-Havlânî", olum: 80, devir: "Tâbiîn", zorluk: 4 },
  { ad: "Ebû Bekir b. Abdirrahman", olum: 94, devir: "Tâbiîn", zorluk: 4 },
  { ad: "Süleymân b. Yesâr", olum: 107, devir: "Tâbiîn", zorluk: 3 },
  { ad: "Hârice b. Zeyd b. Sâbit", olum: 100, devir: "Tâbiîn", zorluk: 4 },
  { ad: "Ubeydullah b. Abdillâh b. Utbe", olum: 98, devir: "Tâbiîn", zorluk: 4 },
  { ad: "Ebû Seleme b. Abdirrahman", olum: 94, devir: "Tâbiîn", zorluk: 3 },
  { ad: "Amr b. Dînâr", olum: 126, devir: "Tâbiîn", zorluk: 3 },
  { ad: "Ebû İshak es-Sebîî", olum: 127, devir: "Tâbiîn", zorluk: 3 },
  { ad: "Yahyâ b. Ebî Kesîr", olum: 129, devir: "Tâbiîn", zorluk: 3 },
  { ad: "Sâbit el-Bünânî", olum: 127, devir: "Tâbiîn", zorluk: 3 },
  { ad: "Eyyûb es-Sahtiyânî", olum: 131, devir: "Tâbiîn", zorluk: 2 },
  { ad: "Hakem b. Uteybe", olum: 115, devir: "Tâbiîn", zorluk: 4 },
  { ad: "Hammâd b. Ebî Süleymân", olum: 120, devir: "Tâbiîn", zorluk: 3 },
  { ad: "Zeyd b. Eslem", olum: 136, devir: "Tâbiîn", zorluk: 3 },
  { ad: "Yahyâ b. Saîd el-Ensârî", olum: 143, devir: "Tâbiîn", zorluk: 3 },
  { ad: "Rabîa b. Ebî Abdirrahman (Rabîatü'r-re'y)", olum: 136, devir: "Tâbiîn", zorluk: 3 },
  { ad: "Muhammed b. el-Münkedir", olum: 130, devir: "Tâbiîn", zorluk: 3 },
  { ad: "Vehb b. Münebbih", olum: 114, devir: "Tâbiîn", zorluk: 3 },
  { ad: "Saîd b. Cübeyr", olum: 94, devir: "Tâbiîn", zorluk: 2 },
  { ad: "Dahhâk b. Müzâhim", olum: 105, devir: "Tâbiîn", zorluk: 4 },
  { ad: "Hişâm b. Urve", olum: 146, devir: "Tâbiîn", zorluk: 2 },
  { ad: "Abdullah b. Dînâr", olum: 127, devir: "Tâbiîn", zorluk: 4 },
  { ad: "Ubeydullah b. Ömer el-Ömerî", olum: 147, devir: "Tâbiîn", zorluk: 3 },
  { ad: "Süheyl b. Ebî Sâlih", olum: 138, devir: "Tâbiîn", zorluk: 4 },
  { ad: "Ebû Sâlih Zekvân es-Semmân", olum: 101, devir: "Tâbiîn", zorluk: 4 },
  { ad: "Talha b. Musarrif el-Yâmî", olum: 112, devir: "Tâbiîn", zorluk: 4 },
  { ad: "Muâviye b. Kurre el-Müzenî", olum: 113, devir: "Tâbiîn", zorluk: 4 },
  { ad: "A‘meş", olum: 148, devir: "Tebeu't-tâbiîn", zorluk: 2 },
  { ad: "Evzâî", olum: 157, devir: "Tebeu't-tâbiîn", zorluk: 2 },
  { ad: "Ma‘mer b. Râşid", olum: 153, devir: "Tebeu't-tâbiîn", zorluk: 2 },
  { ad: "İbn Cüreyc", olum: 150, devir: "Tebeu't-tâbiîn", zorluk: 2 },
  { ad: "Süfyân es-Sevrî", olum: 161, devir: "Tebeu't-tâbiîn", zorluk: 1 },
  { ad: "Mâlik b. Enes", olum: 179, devir: "Tebeu't-tâbiîn", zorluk: 1 },
  { ad: "Şu‘be b. el-Haccâc", olum: 160, devir: "Tebeu't-tâbiîn", zorluk: 1 },
  { ad: "Hammâd b. Seleme", olum: 167, devir: "Tebeu't-tâbiîn", zorluk: 2 },
  { ad: "Leys b. Sa‘d", olum: 175, devir: "Tebeu't-tâbiîn", zorluk: 2 },
  { ad: "Hammâd b. Zeyd", olum: 179, devir: "Tebeu't-tâbiîn", zorluk: 2 },
  { ad: "Abdullah b. el-Mübârek", olum: 181, devir: "Tebeu't-tâbiîn", zorluk: 1 },
  { ad: "Vekî‘ b. el-Cerrâh", olum: 197, devir: "Tebeu't-tâbiîn", zorluk: 2 },
  { ad: "Süfyân b. Uyeyne", olum: 198, devir: "Tebeu't-tâbiîn", zorluk: 1 },
  { ad: "Yahyâ b. Saîd el-Kattân", olum: 198, devir: "Tebeu't-tâbiîn", zorluk: 2 },
  { ad: "Abdurrahman b. Mehdî", olum: 198, devir: "Tebeu't-tâbiîn", zorluk: 2 },
  { ad: "İsrâîl b. Yûnus", olum: 160, devir: "Tebeu't-tâbiîn", zorluk: 4 },
  { ad: "Züheyr b. Muâviye", olum: 173, devir: "Tebeu't-tâbiîn", zorluk: 4 },
  { ad: "Şerîk b. Abdillâh en-Nehaî", olum: 177, devir: "Tebeu't-tâbiîn", zorluk: 3 },
  { ad: "Cerîr b. Abdilhamîd", olum: 188, devir: "Tebeu't-tâbiîn", zorluk: 3 },
  { ad: "Abdullah b. İdrîs", olum: 192, devir: "Tebeu't-tâbiîn", zorluk: 3 },
  { ad: "İbn Ebî Zi’b", olum: 159, devir: "Tebeu't-tâbiîn", zorluk: 3 },
  { ad: "Muhammed b. İshak", olum: 151, devir: "Tebeu't-tâbiîn", zorluk: 2 },
  { ad: "İbn Ebî Arûbe", olum: 156, devir: "Tebeu't-tâbiîn", zorluk: 3 },
  { ad: "Ebû Avâne el-Vâsıtî", olum: 176, devir: "Tebeu't-tâbiîn", zorluk: 3 },
  { ad: "Cerîr b. Hâzim", olum: 170, devir: "Tebeu't-tâbiîn", zorluk: 4 },
  { ad: "Hafs b. Giyâs", olum: 194, devir: "Tebeu't-tâbiîn", zorluk: 3 },
  { ad: "Ísâ b. Yûnus", olum: 191, devir: "Tebeu't-tâbiîn", zorluk: 3 },
  { ad: "Velîd b. Müslim", olum: 195, devir: "Tebeu't-tâbiîn", zorluk: 3 },
  { ad: "İsmâîl b. Ayyâş", olum: 181, devir: "Tebeu't-tâbiîn", zorluk: 4 },
  { ad: "Abdullah b. Vehb", olum: 197, devir: "Tebeu't-tâbiîn", zorluk: 2 },
  { ad: "İsmâîl İbn Uleyye", olum: 193, devir: "Tebeu't-tâbiîn", zorluk: 3 },
  { ad: "Yezîd b. Hârûn", olum: 206, devir: "Tebeu't-tâbiîn", zorluk: 3 },
  { ad: "Ebû Nuaym el-Fazl b. Dükeyn", olum: 219, devir: "Tebeu't-tâbiîn", zorluk: 3 },
  { ad: "Affân b. Müslim", olum: 220, devir: "Tebeu't-tâbiîn", zorluk: 3 },
  { ad: "Kuteybe b. Saîd", olum: 240, devir: "Tebeu't-tâbiîn", zorluk: 3 },
  { ad: "Hennâd b. es-Serî", olum: 243, devir: "Tebeu't-tâbiîn", zorluk: 4 },
  { ad: "Osmân b. Ebî Şeybe", olum: 239, devir: "Tebeu't-tâbiîn", zorluk: 3 },
  { ad: "Züheyr b. Harb Ebû Hayseme", olum: 234, devir: "Tebeu't-tâbiîn", zorluk: 3 },
  { ad: "Muhammed b. Beşşâr (Bündâr)", olum: 252, devir: "Tebeu't-tâbiîn", zorluk: 3 },
  { ad: "Ka‘nevî, Abdullah b. Mesleme", olum: 221, devir: "Tebeu't-tâbiîn", zorluk: 3 },
  { ad: "Yahyâ b. Yahyâ en-Nîsâbûrî", olum: 226, devir: "Tebeu't-tâbiîn", zorluk: 3 },
  { ad: "Amr b. Ali es-Sayrafî (el-Fellâs)", olum: 249, devir: "Tebeu't-tâbiîn", zorluk: 4 },
  { ad: "Muhammed b. Yahyâ ez-Zühlî", olum: 258, devir: "Tebeu't-tâbiîn", zorluk: 3 },
  { ad: "Ali b. el-Ca‘d", olum: 230, devir: "Tebeu't-tâbiîn", zorluk: 4 },
  { ad: "Ebû Muâviye ed-Darîr", olum: 195, devir: "Tebeu't-tâbiîn", zorluk: 3 },
  { ad: "Mervân b. Muâviye el-Fezârî", olum: 193, devir: "Tebeu't-tâbiîn", zorluk: 4 },
  { ad: "Ebû Âsım ed-Dahhâk b. Mahled", olum: 212, devir: "Tebeu't-tâbiîn", zorluk: 4 },
  { ad: "Ebû Dâvûd et-Tayâlisî", olum: 204, devir: "Musannifler", zorluk: 3 },
  { ad: "Abdürrezzâk b. Hemmâm", olum: 211, devir: "Musannifler", zorluk: 2 },
  { ad: "Saîd b. Mansûr", olum: 227, devir: "Musannifler", zorluk: 3 },
  { ad: "İbn Sa‘d", olum: 230, devir: "Musannifler", zorluk: 2 },
  { ad: "İbn Ebî Şeybe", olum: 235, devir: "Musannifler", zorluk: 2 },
  { ad: "İshak b. Râhûye", olum: 238, devir: "Musannifler", zorluk: 2 },
  { ad: "Halîfe b. Hayyât", olum: 240, devir: "Musannifler", zorluk: 4 },
  { ad: "Ahmed b. Hanbel", olum: 241, devir: "Musannifler", zorluk: 1 },
  { ad: "Humeydî, Abdullah b. ez-Zübeyr", olum: 219, devir: "Musannifler", zorluk: 3 },
  { ad: "Abd b. Humeyd", olum: 249, devir: "Musannifler", zorluk: 4 },
  { ad: "Dârimî", olum: 255, devir: "Musannifler", zorluk: 2 },
  { ad: "Buhârî", olum: 256, devir: "Musannifler", zorluk: 1 },
  { ad: "Müslim", olum: 261, devir: "Musannifler", zorluk: 1 },
  { ad: "İbn Mâce", olum: 273, devir: "Musannifler", zorluk: 1 },
  { ad: "Ebû Dâvûd es-Sicistânî", olum: 275, devir: "Musannifler", zorluk: 1 },
  { ad: "Tirmizî", olum: 279, devir: "Musannifler", zorluk: 1 },
  { ad: "İbn Ebi'd-Dünyâ", olum: 281, devir: "Musannifler", zorluk: 4 },
  { ad: "Hâris b. Ebî Üsâme", olum: 282, devir: "Musannifler", zorluk: 5 },
  { ad: "Bezzâr", olum: 292, devir: "Musannifler", zorluk: 3 },
  { ad: "Muhammed b. Nasr el-Mervezî", olum: 294, devir: "Musannifler", zorluk: 4 },
  { ad: "Nesâî", olum: 303, devir: "Musannifler", zorluk: 1 },
  { ad: "İbnü'l-Cârûd", olum: 307, devir: "Musannifler", zorluk: 5 },
  { ad: "İbn Huzeyme", olum: 311, devir: "Musannifler", zorluk: 2 },
  { ad: "Ebû Avâne el-İsferâyînî", olum: 316, devir: "Musannifler", zorluk: 3 },
  { ad: "Bagavî, Abdullah b. Muhammed", olum: 317, devir: "Musannifler", zorluk: 4 },
  { ad: "İbn Sâid, Yahyâ b. Muhammed", olum: 318, devir: "Musannifler", zorluk: 5 },
  { ad: "Taberânî", olum: 360, devir: "Musannifler", zorluk: 2 },
  { ad: "Dârekutnî", olum: 385, devir: "Musannifler", zorluk: 2 },
  { ad: "İbn Mende", olum: 395, devir: "Musannifler", zorluk: 4 },
  { ad: "Hâkim en-Nîsâbûrî", olum: 405, devir: "Musannifler", zorluk: 2 },
  { ad: "Temmâm er-Râzî", olum: 414, devir: "Musannifler", zorluk: 5 },
  { ad: "Ebû Nuaym el-İsfahânî", olum: 430, devir: "Musannifler", zorluk: 3 },
  { ad: "Kudâî", olum: 454, devir: "Musannifler", zorluk: 4 },
  { ad: "Beyhakī", olum: 458, devir: "Musannifler", zorluk: 2 },
  { ad: "Ziyâ el-Makdisî", olum: 643, devir: "Musannifler", zorluk: 4 },
  { ad: "Yahyâ b. Maîn", olum: 233, devir: "Ricâl ve ilel", zorluk: 2 },
  { ad: "Ali b. el-Medînî", olum: 234, devir: "Ricâl ve ilel", zorluk: 2 },
  { ad: "Cûzcânî", olum: 259, devir: "Ricâl ve ilel", zorluk: 4 },
  { ad: "İclî", olum: 261, devir: "Ricâl ve ilel", zorluk: 4 },
  { ad: "Ya‘kūb b. Şeybe", olum: 262, devir: "Ricâl ve ilel", zorluk: 4 },
  { ad: "Ebû Zür‘a er-Râzî", olum: 264, devir: "Ricâl ve ilel", zorluk: 2 },
  { ad: "Ebû Hâtim er-Râzî", olum: 277, devir: "Ricâl ve ilel", zorluk: 2 },
  { ad: "Fesevî, Ya‘kūb b. Süfyân", olum: 277, devir: "Ricâl ve ilel", zorluk: 4 },
  { ad: "Berdîcî", olum: 301, devir: "Ricâl ve ilel", zorluk: 5 },
  { ad: "Sâcî, Zekeriyyâ b. Yahyâ", olum: 307, devir: "Ricâl ve ilel", zorluk: 5 },
  { ad: "Dûlâbî, Ebû Bişr", olum: 310, devir: "Ricâl ve ilel", zorluk: 5 },
  { ad: "Ukaylî", olum: 322, devir: "Ricâl ve ilel", zorluk: 3 },
  { ad: "İbn Ebî Hâtim", olum: 327, devir: "Ricâl ve ilel", zorluk: 2 },
  { ad: "İbn Hibbân", olum: 354, devir: "Ricâl ve ilel", zorluk: 2 },
  { ad: "İbn Adî", olum: 365, devir: "Ricâl ve ilel", zorluk: 3 },
  { ad: "Ebû Ahmed el-Hâkim", olum: 378, devir: "Ricâl ve ilel", zorluk: 5 },
  { ad: "İbn Şâhîn", olum: 385, devir: "Ricâl ve ilel", zorluk: 4 },
  { ad: "Hamza es-Sehmî", olum: 427, devir: "Ricâl ve ilel", zorluk: 5 },
  { ad: "Halîlî, Ebû Ya‘lâ", olum: 446, devir: "Ricâl ve ilel", zorluk: 5 },
  { ad: "Hatîb el-Bağdâdî", olum: 463, devir: "Ricâl ve ilel", zorluk: 2 },
  { ad: "İbnü'l-Kayserânî", olum: 507, devir: "Ricâl ve ilel", zorluk: 4 },
  { ad: "İbnü'l-Kattân el-Fâsî", olum: 628, devir: "Ricâl ve ilel", zorluk: 4 },
  { ad: "Mizzî", olum: 742, devir: "Ricâl ve ilel", zorluk: 2 },
  { ad: "İbn Abdilhâdî", olum: 744, devir: "Ricâl ve ilel", zorluk: 4 },
  { ad: "Zehebî", olum: 748, devir: "Ricâl ve ilel", zorluk: 1 },
  { ad: "Alâî, Salâhaddin", olum: 761, devir: "Ricâl ve ilel", zorluk: 4 },
  { ad: "Moğultay b. Kılıç", olum: 762, devir: "Ricâl ve ilel", zorluk: 4 },
  { ad: "İbn Hacer el-Askalânî", olum: 852, devir: "Ricâl ve ilel", zorluk: 1 },
  { ad: "İbn Kutluboğa", olum: 879, devir: "Ricâl ve ilel", zorluk: 5 },
  { ad: "Şâfiî", olum: 204, devir: "Usûl ve şerh", zorluk: 1 },
  { ad: "Râmhürmüzî", olum: 360, devir: "Usûl ve şerh", zorluk: 3 },
  { ad: "Hattâbî", olum: 388, devir: "Usûl ve şerh", zorluk: 3 },
  { ad: "İbn Battâl", olum: 449, devir: "Usûl ve şerh", zorluk: 4 },
  { ad: "İbn Hazm", olum: 456, devir: "Usûl ve şerh", zorluk: 2 },
  { ad: "İbn Abdilberr", olum: 463, devir: "Usûl ve şerh", zorluk: 2 },
  { ad: "Bâcî, Ebü'l-Velîd", olum: 474, devir: "Usûl ve şerh", zorluk: 4 },
  { ad: "Begavî, Muhyissünne", olum: 516, devir: "Usûl ve şerh", zorluk: 2 },
  { ad: "İbnü'l-Arabî el-Meâfirî", olum: 543, devir: "Usûl ve şerh", zorluk: 3 },
  { ad: "Kādî İyâz", olum: 544, devir: "Usûl ve şerh", zorluk: 2 },
  { ad: "İbn Beşküvâl", olum: 578, devir: "Usûl ve şerh", zorluk: 4 },
  { ad: "İbnü'l-Cevzî", olum: 597, devir: "Usûl ve şerh", zorluk: 2 },
  { ad: "İbnü'l-Esîr, Mecdüddin", olum: 606, devir: "Usûl ve şerh", zorluk: 3 },
  { ad: "İbnü's-Salâh", olum: 643, devir: "Usûl ve şerh", zorluk: 1 },
  { ad: "Kurtubî, Ebü'l-Abbâs", olum: 656, devir: "Usûl ve şerh", zorluk: 4 },
  { ad: "Münzirî", olum: 656, devir: "Usûl ve şerh", zorluk: 3 },
  { ad: "Nevevî", olum: 676, devir: "Usûl ve şerh", zorluk: 1 },
  { ad: "İbn Dakīkul‘îd", olum: 702, devir: "Usûl ve şerh", zorluk: 3 },
  { ad: "İbn Seyyidünnâs", olum: 734, devir: "Usûl ve şerh", zorluk: 4 },
  { ad: "Tîbî", olum: 743, devir: "Usûl ve şerh", zorluk: 4 },
  { ad: "İbn Kesîr", olum: 774, devir: "Usûl ve şerh", zorluk: 1 },
  { ad: "Kirmânî", olum: 786, devir: "Usûl ve şerh", zorluk: 4 },
  { ad: "Zerkeşî, Bedreddin", olum: 794, devir: "Usûl ve şerh", zorluk: 3 },
  { ad: "İbn Receb el-Hanbelî", olum: 795, devir: "Usûl ve şerh", zorluk: 2 },
  { ad: "İbnü'l-Mülakkın", olum: 804, devir: "Usûl ve şerh", zorluk: 4 },
  { ad: "Bulkīnî, Sirâcüddin", olum: 805, devir: "Usûl ve şerh", zorluk: 4 },
  { ad: "Irâkī, Zeynüddin", olum: 806, devir: "Usûl ve şerh", zorluk: 2 },
  { ad: "Heysemî", olum: 807, devir: "Usûl ve şerh", zorluk: 3 },
  { ad: "Aynî", olum: 855, devir: "Usûl ve şerh", zorluk: 2 },
  { ad: "Bikāî", olum: 885, devir: "Usûl ve şerh", zorluk: 5 },
  { ad: "Sehâvî", olum: 902, devir: "Usûl ve şerh", zorluk: 2 },
  { ad: "Süyûtî", olum: 911, devir: "Usûl ve şerh", zorluk: 1 },
  { ad: "Kastallânî", olum: 923, devir: "Usûl ve şerh", zorluk: 3 },
  { ad: "Zekeriyyâ el-Ensârî", olum: 926, devir: "Usûl ve şerh", zorluk: 3 },
  { ad: "İbn Hacer el-Heytemî", olum: 974, devir: "Usûl ve şerh", zorluk: 3 },
  { ad: "Ali el-Kārî", olum: 1014, devir: "Geç dönem", zorluk: 2 },
  { ad: "Münâvî", olum: 1031, devir: "Geç dönem", zorluk: 3 },
  { ad: "Zürkānî, Muhammed b. Abdilbâkī", olum: 1122, devir: "Geç dönem", zorluk: 4 },
  { ad: "Sindî, Ebü'l-Hasen", olum: 1138, devir: "Geç dönem", zorluk: 4 },
  { ad: "Aclûnî", olum: 1162, devir: "Geç dönem", zorluk: 3 },
  { ad: "Şah Veliyyullah ed-Dihlevî", olum: 1176, devir: "Geç dönem", zorluk: 2 },
  { ad: "Zebîdî, Murtazâ", olum: 1205, devir: "Geç dönem", zorluk: 3 },
  { ad: "Şevkânî", olum: 1250, devir: "Geç dönem", zorluk: 2 },
  { ad: "Leknevî", olum: 1304, devir: "Geç dönem", zorluk: 3, miladi: 1886 },
  { ad: "Sıddîk Hasan Han", olum: 1307, devir: "Geç dönem", zorluk: 4, miladi: 1890 },
  { ad: "Gümüşhânevî, Ahmed Ziyâüddin", olum: 1311, devir: "Geç dönem", zorluk: 3, miladi: 1893 },
  { ad: "Kettânî, Muhammed b. Ca‘fer", olum: 1345, devir: "Geç dönem", zorluk: 4, miladi: 1927 },
  { ad: "Babanzâde Ahmed Naim", olum: 1353, devir: "Geç dönem", zorluk: 3, miladi: 1934 },
  { ad: "Zâhid el-Kevserî", olum: 1371, devir: "Geç dönem", zorluk: 3, miladi: 1952 },
  { ad: "Kâmil Miras", olum: 1376, devir: "Geç dönem", zorluk: 3, miladi: 1957 },
  { ad: "Ahmed Muhammed Şâkir", olum: 1377, devir: "Geç dönem", zorluk: 2, miladi: 1958 },
  { ad: "Mustafa es-Sibâî", olum: 1384, devir: "Geç dönem", zorluk: 3, miladi: 1964 },
  { ad: "Abdurrahman el-Muallimî", olum: 1386, devir: "Geç dönem", zorluk: 4, miladi: 1966 },
  { ad: "Abdülfettâh Ebû Gudde", olum: 1417, devir: "Geç dönem", zorluk: 3, miladi: 1997 },
  { ad: "Elbânî", olum: 1420, devir: "Geç dönem", zorluk: 2, miladi: 1999 },
  { ad: "Şuayb el-Arnaût", olum: 1438, devir: "Geç dönem", zorluk: 3, miladi: 2016 },
  { ad: "Muhammed Mustafa el-A‘zamî", olum: 1439, devir: "Geç dönem", zorluk: 3, miladi: 2017 },
  { ad: "Nûreddin Itr", olum: 1442, devir: "Geç dönem", zorluk: 3, miladi: 2020 },
];
